(function(global){
 'use strict';
 if(global.__webrSubscriptionPage)return;global.__webrSubscriptionPage=true;
 const t=(s,v)=>global.WebRI18n?.t(s,v)||s.replace(/\{(\w+)\}/g,(m,k)=>v?.[k]??m);
 const E=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;};
 const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
 const productsIDs=['3fe38b90-6cf9-45de-b732-2933ef100347','ac3d82de-e6a5-4a48-8029-5f59d22749fa','356e84f3-211c-4ac7-8aee-ca6f75017134','3e9192d3-b535-4047-929f-033ad6b02326'];
 const productNames=['정회원','VIP회원','정회원 팀','VIP회원 팀'];
 const state={products:[],settings:{},subscriptions:[],provider:'toss',interval:'month',product:productsIDs[0],teamProduct:productsIDs[2],quantity:1,consent:false,busy:false,busyId:'',rowFeedback:null,listFeedback:null,expandedIds:new Set(),loaded:false,message:'',error:false,login:false,request:null,confirmCancel:'',userinfo:null,userInfoPending:false,catalogError:false,configError:false,catalogPending:false,configPending:false,listsComplete:false,listPending:true};
 let host,callback,closed=false,poll=0,pollCount=0,sdkPromise;
 const lang=()=>global.WebRI18n?.language||'ko';
 const money=(minor,currency)=>new Intl.NumberFormat(lang(),{style:'currency',currency:currency||'KRW'}).format(Number(minor)/(currency==='USD'?100:1));
 const date=value=>value?new Intl.DateTimeFormat(lang(),{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Seoul'}).format(new Date(value)):t('결제 확인 후 표시됩니다.');
 const product=()=>state.products.find(p=>p.uuid===state.product);
 const team=()=>!!product()?.seat_priced;
 const settings=()=>state.settings[state.provider]||{};
 const unit=()=>Number(settings().prices?.[state.product]?.[state.interval]||0);
 const total=()=>unit()*(team()?state.quantity:1);
 const name=id=>t(productNames[productsIDs.indexOf(id)]||'정기구독');
 const intervalText=value=>t(value==='year'?'연별 결제':'월별 결제');
 const api=async(path,body,timeoutMs)=>{const controller=timeoutMs?new AbortController():null,timer=controller?setTimeout(()=>controller.abort(),timeoutMs):null;try{const r=await fetch(path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',...(controller?{signal:controller.signal}:{}),...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});let p;try{p=await r.json();}catch(_){throw Error('unavailable');}if(!r.ok||p.ok===false)throw Error(r.status===401?'authentication_required':p.error?.code||'unavailable');return p.data??p;}finally{if(timer)clearTimeout(timer);}};
 const base=(provider,id)=>'/api/subscriptions/'+provider+'/'+(id?encodeURIComponent(id)+'/':'');
 function node(tag,source,cls){return E(tag,t(source),cls);}
 function button(source,fn,primary=false){const b=node('button',source,primary?'sub-button primary':'sub-button');b.type='button';b.disabled=state.busy;b.addEventListener('click',fn);return b;}
 function link(source,href){const a=node('a',source,'sub-button');a.href=href;return a;}
 function message(error){state.error=true;state.message=error.message==='authentication_required'?'로그인이 필요합니다.':error.message==='quote_changed'?'가격이 변경되었습니다. 새 가격을 확인한 뒤 다시 선택해 주세요.':['subscription_exists','active_subscription_exists','subscription_already_exists'].includes(error.message)?'같은 유형의 구독이 이미 있습니다. 내 구독에서 관리해 주세요.':error.message==='approval_unavailable'?'현재 승인 링크를 확인할 수 없습니다. 구독 상태를 다시 확인하거나 신청을 취소해 주세요.':error.message==='subscription_reconciliation_required'?'결제 신청 결과를 확인할 수 없습니다. 구독 상태를 다시 확인하고, 계속되면 고객센터에 문의해 주세요.':error.message==='payment_environment_mismatch'?'현재 서버의 결제 환경에서 관리할 수 없습니다.':error.message==='review_required'?'결제 상태 확인 필요':'요청을 완료하지 못했습니다. 내 구독에서 상태를 확인해 주세요.';if(error.message==='authentication_required')state.login=true;}
 function reset(){state.consent=false;state.request=null;state.message='';state.error=false;}
 function mountStyles(){if(document.getElementById('webr-subscription-style'))return;const s=E('style');s.id='webr-subscription-style';s.textContent=`
 .webr-subscription{width:calc(100% - 32px);max-width:1120px;margin:36px auto 70px;color:#0f172a;font:15px/1.6 system-ui,sans-serif;min-width:0}.webr-subscription *{box-sizing:border-box}.webr-subscription h1{font-size:32px;line-height:1.2;font-weight:800;margin:0 0 14px}.webr-subscription h2{font-size:22px;font-weight:750;margin:0 0 16px}.webr-subscription h3{font-size:18px;font-weight:700;margin:0 0 8px}.sub-muted{color:#64748b}.sub-nav,.sub-actions,.sub-segment{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0}.sub-button{display:inline-flex;align-items:center;justify-content:center;gap:6px;min-height:44px;padding:9px 16px;border:1px solid #cbd5e1;border-radius:10px;background:white;color:#334155;text-decoration:none;font:inherit;font-weight:650;cursor:pointer;white-space:normal;text-align:center;overflow-wrap:anywhere}.sub-button.primary,.sub-button[aria-pressed=true]{color:white;background:#1d4ed8;border-color:#1d4ed8}.sub-button:disabled{opacity:.5;cursor:wait}.sub-button:focus-visible,.webr-subscription input:focus-visible{outline:3px solid #60a5fa;outline-offset:3px}.sub-grid{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(0,1fr);gap:22px;margin:26px 0}.sub-panel{min-width:0;padding:26px;border:1px solid #e2e8f0;border-radius:18px;background:white;box-shadow:0 6px 24px #0f172a05}.sub-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:18px 0}.sub-options .sub-button{justify-content:flex-start;min-height:66px}.sub-price{font-size:30px;font-weight:800;line-height:1.3;margin:12px 0;overflow-wrap:anywhere}.sub-note{padding:14px 16px;border-radius:10px;background:#eff6ff;color:#1e40af;margin:16px 0;overflow-wrap:anywhere}.sub-note.error{background:#fff7ed;color:#9a3412}.sub-check{display:flex;align-items:flex-start;gap:10px;margin:22px 0}.sub-check input{flex:none;width:18px;height:18px;margin-top:4px}.sub-quantity{display:block;width:100%;max-width:160px;padding:10px;border:1px solid #cbd5e1;border-radius:9px;font:inherit}.sub-id{font:12px/1.6 ui-monospace,monospace;color:#64748b;overflow-wrap:anywhere}.sub-list{display:grid;gap:14px;margin:18px 0}.sub-row{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;flex-wrap:wrap}.sub-detail{display:grid;grid-template-columns:auto minmax(0,1fr);gap:7px 18px;margin:14px 0}.sub-detail dd{margin:0;overflow-wrap:anywhere}.sub-detail dt{color:#64748b}.sub-confirm{padding:16px;border:1px solid #fdba74;background:#fff7ed;border-radius:12px;width:100%}@media(max-width:700px){.sub-grid{grid-template-columns:minmax(0,1fr)}.sub-panel{padding:20px}.webr-subscription{margin-top:24px}.webr-subscription h1{font-size:27px}.sub-price{font-size:27px}.sub-detail{grid-template-columns:minmax(0,1fr);gap:2px}.sub-detail dd{margin-bottom:10px}.sub-options{grid-template-columns:minmax(0,1fr)}}`;
 s.textContent+=`.webr-payment-tabs{display:flex;gap:0;align-items:stretch;margin:0 0 30px;border-bottom:2px solid #dbe3ef}.webr-payment-tabs .sub-button{min-width:160px;margin-bottom:-2px;border:0;border-bottom:3px solid transparent;border-radius:0;background:transparent;color:#64748b;font-size:16px}.webr-payment-tabs .sub-button[aria-current=page]{border-color:#2563eb;color:#1d4ed8;background:#eff6ff}.webr-payment-tabs .sub-button:focus-visible{position:relative;z-index:1}.sub-offer-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:16px 0 22px}.sub-offer-card{display:flex;min-width:0;flex-direction:column;gap:10px;padding:20px;border:1px solid #dbe3ef;border-radius:16px;background:#fff;box-shadow:0 5px 18px #0f172a09}.sub-offer-card[aria-selected=true]{border-color:#2563eb;box-shadow:0 0 0 2px #dbeafe}.sub-offer-card h3{margin:0}.sub-offer-card .sub-price{font-size:24px;margin:0}.sub-offer-card .sub-button{width:100%;margin-top:auto}.sub-offer-card ul{padding-left:20px;margin:0;color:#475569;font-size:13px}.sub-offer-card li+li{margin-top:4px}@media(max-width:800px){.sub-offer-grid{grid-template-columns:minmax(0,1fr)}}@media(max-width:480px){.webr-payment-tabs .sub-button{min-width:0;flex:1;padding:9px 8px;font-size:14px}}`;
  s.textContent+=`.webr-subscription{max-width:1500px;padding:0 4px}.webr-subscription h1{display:inline-block;text-decoration:underline;text-decoration-color:#60a5fa;text-decoration-thickness:7px;text-underline-offset:5px}.sub-grid{grid-template-columns:minmax(245px,1.05fr) repeat(3,minmax(0,1fr));align-items:stretch;gap:16px}.sub-panel{padding:24px}.sub-check{margin:16px 0}.sub-check span{line-height:1.45}.sub-summary{background:#eff6ff;border-color:#bfdbfe}.sub-summary .sub-button.primary{width:100%}.sub-offer-card{height:100%;padding:24px;text-align:center}.sub-offer-card h2{margin:0;font-size:23px}.sub-offer-card .sub-button{margin-top:16px}.sub-offer-card .sub-muted{font-size:14px;line-height:1.6}.sub-offer-card ul{text-align:left;margin-top:22px}.sub-offer-card fieldset{min-width:0;border:0;padding:0;margin:16px 0;text-align:left}.sub-offer-card legend{font-weight:700;margin-bottom:8px}.sub-team-choice{display:flex;gap:8px;align-items:center;padding:8px;border:1px solid #dbe3ef;border-radius:8px;margin:6px 0;font-size:14px}.sub-team-choice input{flex:none}.sub-team-choice[aria-checked=true]{border-color:#93c5fd;background:#eff6ff}.sub-offer-card .sub-quantity{max-width:none}.sub-offer-card .sub-quantity-label{display:block;text-align:left;font-weight:650}.sub-summary dl{margin:8px 0 16px}.sub-summary dt{display:inline;font-weight:700}.sub-summary dd{display:inline;margin:0;overflow-wrap:anywhere}.sub-summary dl>div{margin:4px 0}.sub-segment .sub-button{flex:1;min-width:0}.sub-offer-card .sub-price{font-size:24px}.sub-price-unavailable{font-size:19px;color:#9a3412}.sub-offer-card .sub-button[aria-pressed=true]{cursor:default}@media(max-width:1050px){.sub-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){.sub-grid{grid-template-columns:minmax(0,1fr)}.sub-offer-card{min-height:0}}`;
  s.textContent+=`.sub-list{gap:8px}.sub-history-row{padding:11px 14px;box-shadow:none}.sub-history-main{display:grid;grid-template-columns:minmax(0,1fr) auto auto auto;align-items:center;gap:8px 14px}.sub-history-heading{display:flex;align-items:baseline;gap:5px 10px;min-width:0;flex-wrap:wrap}.sub-history-heading h3,.sub-history-heading p{margin:0}.sub-history-heading h3{font-size:16px}.sub-history-heading .sub-muted{font-size:13px}.sub-history-amount{font-weight:700;white-space:nowrap}.sub-history-status{margin:0;padding:4px 9px;border-radius:999px;background:#eff6ff;color:#1e40af;font-size:13px;white-space:nowrap}.sub-history-actions{display:flex;align-items:center;justify-content:flex-end;gap:6px;flex-wrap:wrap;margin:0}.sub-history-actions .sub-button{min-height:32px;padding:4px 9px;font-size:13px}.sub-history-details{margin:10px 0 0;padding:10px 0 0;border-top:1px solid #e2e8f0}.sub-history-details .sub-detail{margin:0 0 8px}.sub-history-details .sub-id{margin:0}.sub-history-feedback{margin:8px 0 0;padding:8px 10px;font-size:13px}.sub-history-row .sub-confirm{margin-top:10px;padding:10px 12px}.sub-history-row .sub-confirm p{margin:0 0 8px}.sub-history-row .sub-confirm .sub-button{min-height:34px;margin-right:6px;padding:5px 10px;font-size:13px}@media(max-width:850px){.sub-history-main{grid-template-columns:minmax(0,1fr) auto}.sub-history-actions{grid-column:1/-1;justify-content:flex-start}}@media(max-width:480px){.sub-history-main{gap:5px 8px}.sub-history-heading{grid-column:1/-1}.sub-history-amount{font-size:14px}.sub-history-status{font-size:12px}.sub-history-actions .sub-button{min-height:34px}}`;
  document.head.append(s);}
 function selectProduct(id){const p=state.products.find(item=>item.uuid===id);if(!p)return;state.product=id;if(p.seat_priced){state.teamProduct=id;state.quantity=Math.min(Number(p.max_quantity)||500,Math.max(Number(p.min_quantity)||1,state.quantity));}else state.quantity=1;reset();render();}
 function detail(dl,label,value,privateValue=false){if(!value)return;const row=E('div');row.append(E('dt',t(label)+' '));const dd=E('dd',String(value));if(privateValue)dd.dataset.webrUserContent='';row.append(dd);dl.append(row);}
 function features(card,p){if(!Array.isArray(p?.features)||!p.features.length)return;const list=E('ul');p.features.forEach(feature=>{const item=E('li');item.append(E('span','✓ '),E('span',t(feature)));list.append(item);});card.append(list);}
 function render(){if(!host||closed)return;const savedFocus=document.activeElement?.id;host.replaceChildren();const page=E('main',null,'webr-subscription');page.dataset.webrUi='';page.dataset.subscriptionPage='';
  const nav=E('nav',null,'webr-payment-tabs');nav.setAttribute('aria-label',t('결제 방식'));nav.append(link('일시결제','/intro/membership/'));const current=link('정기구독','/intro/membership/subscription/');current.setAttribute('aria-current','page');nav.append(current);page.append(nav,node('h1','정기구독'));
  if(state.message){const notice=node('p',state.message,'sub-note'+(state.error?' error':''));notice.setAttribute('role','status');page.append(notice);}
  if(state.catalogError||state.configError){const notice=node('p',state.catalogError?'이용권 정보를 불러오지 못했습니다. 다시 확인해 주세요.':'정기구독 결제 수단을 이용할 수 없습니다. 다시 확인해 주세요.','sub-note error');notice.setAttribute('role','status');page.append(notice);}
  if(callback){renderCallback(page);host.append(page);return;}
  if(!state.loaded){page.append(node('p','불러오는 중입니다.','sub-note'));host.append(page);return;}
  const grid=E('div',null,'sub-grid'),summary=E('aside',null,'sub-panel sub-summary');summary.append(node('h2','내 멤버십과 결제'));
  if(state.userinfo){const dl=E('dl');detail(dl,'계정:',state.userinfo.email,true);detail(dl,'현재 등급:',state.userinfo.role);detail(dl,'현재 만료일:',state.userinfo.expired_at);detail(dl,'선택 상품:',product()?.title||name(state.product));summary.append(dl);}
  else if(global.gv_username){summary.append(node('p',state.userInfoPending?'회원 정보를 확인하고 있습니다.':'회원 정보를 확인할 수 없습니다.','sub-muted'));}
  else{summary.append(node('p','로그인 후 구독을 시작할 수 있습니다.','sub-muted'),link('로그인','/account/?next='+encodeURIComponent('/intro/membership/subscription/')));}
  summary.append(node('h3','결제 주기'));const intervals=E('div',null,'sub-segment');for(const [key,label] of [['month','월별 결제'],['year','연별 결제']]){const b=button(label,()=>{state.interval=key;reset();render();});b.id='sub-interval-'+key;b.setAttribute('aria-pressed',String(state.interval===key));intervals.append(b);}summary.append(intervals);
  summary.append(node('h3','결제 수단'));const providers=E('div',null,'sub-segment');for(const [key,label] of [['toss','카드 자동결제'],['paypal','PayPal']]){const b=button(label,()=>{state.provider=key;reset();render();});b.id='sub-provider-'+key;b.setAttribute('aria-pressed',String(state.provider===key));providers.append(b);}summary.append(providers);
  summary.append(node('h3','결제 예정 금액'));const ready=!!(!state.catalogError&&!state.configError&&!state.catalogPending&&!state.configPending&&settings().enabled&&unit()&&product());const amount=E('p',ready?money(total(),settings().currency):t(state.configPending||state.catalogPending?'가격을 확인하고 있습니다.':'현재 이 결제 수단을 이용할 수 없습니다.'),'sub-price'+(ready?'':' sub-price-unavailable'));amount.id='sub-total';amount.dataset.webrUserContent='';summary.append(amount,E('p',name(state.product)+' · '+intervalText(state.interval),'sub-muted'));
  if(team()&&ready)summary.append(E('p',t('좌석당 {amount} × {quantity}석',{amount:money(unit(),settings().currency),quantity:state.quantity}),'sub-muted'));
  if(!ready){const retry=button('다시 확인',loadInitial);retry.id='sub-config-retry';summary.append(retry);}
  summary.append(node('p','첫 결제는 구독 신청 시 진행됩니다. 이후 선택한 주기마다 자동으로 결제됩니다.','sub-note'),node('p','해지하면 다음 갱신부터 청구가 중단되며, 이미 결제한 이용 기간은 유지됩니다.','sub-muted'));if(state.provider==='toss')summary.append(node('p','결제일이 없는 달에는 해당 월의 마지막 날에 결제됩니다.','sub-muted'),node('p','카드 결제는 최초 시도를 포함해 최대 3회 시도합니다.','sub-muted'));
  const consent=E('label',null,'sub-check'),checkbox=E('input');checkbox.type='checkbox';checkbox.id='sub-consent';checkbox.checked=state.consent;checkbox.disabled=state.busy;checkbox.addEventListener('change',()=>{state.consent=checkbox.checked;render();});consent.append(checkbox,E('span',t('결제 금액, 주기 및 자동 갱신 조건을 확인하고 정기결제에 동의합니다.')));summary.append(consent);
  const start=button(state.busy?'결제창을 준비하고 있습니다.':'구독 시작',create,true);start.id='sub-start';start.disabled=state.busy||!state.consent||!ready;summary.append(start);grid.append(summary);
   for(const i of [0,1]){const id=productsIDs[i],p=state.products.find(item=>item.uuid===id),card=E('article',null,'sub-offer-card');card.dataset.subscriptionCard=i===0?'regular':'vip';card.append(node('h2',p?.title||productNames[i]));if(p?.description)card.append(E('p',t(p.description),'sub-muted'));const price=Number(settings().prices?.[id]?.[state.interval]||0);card.append(E('p',price?money(price,settings().currency):t(state.configPending?'가격을 확인하고 있습니다.':'현재 가격을 확인할 수 없습니다.'),'sub-price'+(price?'':' sub-price-unavailable')));const select=button(state.product===id?'선택됨':'선택',()=>selectProduct(id),state.product===id);select.id='sub-product-'+i;select.setAttribute('aria-label',t(p?.title||productNames[i]));select.setAttribute('aria-pressed',String(state.product===id));select.disabled=!p||state.busy;card.append(select);features(card,p);grid.append(card);}
  const teamCard=E('article',null,'sub-offer-card');teamCard.dataset.subscriptionCard='team';teamCard.append(node('h2','기관/팀 회원'));const teamProduct=state.products.find(p=>p.uuid===state.teamProduct)||state.products.find(p=>p.seat_priced);if(teamProduct?.description)teamCard.append(E('p',t(teamProduct.description),'sub-muted'));const teamPrice=Number(settings().prices?.[teamProduct?.uuid]?.[state.interval]||0);teamCard.append(E('p',teamPrice?money(teamPrice,settings().currency)+' /명':t('현재 가격을 확인할 수 없습니다.'),'sub-price'+(teamPrice?'':' sub-price-unavailable')));
  const roles=E('fieldset'),legend=node('legend','팀원 등급');roles.append(legend);for(const i of [2,3]){const id=productsIDs[i],p=state.products.find(item=>item.uuid===id),label=E('label',null,'sub-team-choice'),radio=E('input');radio.type='radio';radio.name='sub-team-role';radio.id='sub-team-'+i;radio.value=id;radio.checked=team()&&state.teamProduct===id;radio.disabled=!p||state.busy;radio.addEventListener('change',()=>selectProduct(id));label.setAttribute('aria-checked',String(radio.checked));const price=Number(settings().prices?.[id]?.[state.interval]||0);label.append(radio,E('span',t(p?.title||productNames[i])),E('span',price?money(price,settings().currency)+' /명':''));roles.append(label);}teamCard.append(roles);
  const qLabel=node('label','추가 팀원 수','sub-quantity-label');qLabel.htmlFor='sub-quantity';const q=E('input',null,'sub-quantity');q.id='sub-quantity';q.type='number';q.min=String(Math.max(0,(Number(teamProduct?.min_quantity)||1)-1));q.max=String(Math.max(0,(Number(teamProduct?.max_quantity)||500)-1));q.step='1';q.value=String(Math.max(0,(team()?state.quantity:Math.max(Number(teamProduct?.min_quantity)||1,1))-1));q.disabled=!teamProduct||state.busy;q.addEventListener('change',()=>{const count=Math.min(Number(q.max),Math.max(Number(q.min),Math.floor(Number(q.value)||0)));if(count+1===state.quantity&&state.product===teamProduct.uuid)return;state.product=teamProduct.uuid;state.quantity=count+1;reset();render();});teamCard.append(qLabel,q,node('p',t('본인 포함 전체 {quantity}석',{quantity:team()?state.quantity:Math.max(Number(teamProduct?.min_quantity)||1,1)}),'sub-muted'));
  const teamSelect=button(team()?'선택됨':'선택',()=>selectProduct(teamProduct?.uuid),team());teamSelect.id='sub-product-team';teamSelect.setAttribute('aria-label',t('기관/팀 회원'));teamSelect.setAttribute('aria-pressed',String(team()));teamSelect.disabled=!teamProduct||state.busy;teamCard.append(teamSelect);features(teamCard,teamProduct);grid.append(teamCard);page.append(grid);
  const mine=E('section');mine.append(node('h2','내 구독'),node('p','다음 결제일은 한국 시간 기준입니다.','sub-muted'));if(!state.listsComplete)mine.append(node('p',state.listPending?'구독 내역을 확인하고 있습니다.':'구독 내역을 모두 확인할 수 없습니다. 다시 확인해 주세요.','sub-note'+(state.listPending?'':' error')));else if(!state.subscriptions.length)mine.append(node('p','이용 중인 구독이 없습니다.','sub-note'));const list=E('div',null,'sub-list');state.subscriptions.forEach(s=>list.append(subscriptionCard(s)));const refreshButton=button('다시 확인',()=>refresh(true));refreshButton.id='sub-history-refresh';mine.append(list,refreshButton);if(state.listFeedback){const note=node('p',state.listFeedback.text,'sub-history-feedback sub-note'+(state.listFeedback.error?' error':''));note.setAttribute('role','status');mine.append(note);}page.append(mine);host.append(page);if(savedFocus)document.getElementById(savedFocus)?.focus({preventScroll:true});}
 const statusLabel=s=>s.review_required?'결제 상태 확인 필요':['active','ACTIVE'].includes(s.status)&&!s.period_end?'결제 처리 중':({pending_card:'카드 등록 대기',APPROVAL_PENDING:'승인 대기',APPROVED:'결제 처리 중',ACTIVE:'구독 중',active:'구독 중',past_due:'결제 실패',paused:'일시정지',SUSPENDED:'일시정지',canceled:'해지됨',CANCELLED:'해지됨',EXPIRED:'만료됨'})[s.status]||'결제 처리 중';
 const unpaidApplication=s=>s.provider==='paypal'&&!s.period_end&&!s.granted&&['CREATING','CREATE_UNKNOWN','APPROVAL_PENDING','APPROVED'].includes(s.status);
 const otherEnvironment=s=>s.provider==='paypal'&&['live','sandbox'].includes(s.environment)&&['live','sandbox'].includes(state.settings.paypal?.environment)&&s.environment!==state.settings.paypal.environment;
 function subscriptionCard(s){
  const panel=E('article',null,'sub-panel sub-history-row'),row=E('div',null,'sub-history-main'),heading=E('div',null,'sub-history-heading');panel.dataset.subscriptionId=s.id;
  heading.append(E('h3',name(s.product_id)),E('p',(s.provider==='paypal'?'PayPal'+(otherEnvironment(s)?' ('+s.environment+')':''):t('카드 자동결제'))+' · '+intervalText(s.interval),'sub-muted'));
  const amount=E('strong',money(s.amount_minor,s.currency),'sub-history-amount');amount.dataset.webrUserContent='';
  const status=node('span',statusLabel(s)+(unpaidApplication(s)?' · '+t('결제 전'):'')+(otherEnvironment(s)?' · '+t('다른 결제 환경'):''),'sub-history-status');status.dataset.webrUserContent='';
  const actions=E('div',null,'sub-history-actions');const actionButton=(label,action,fn)=>{const b=button(label,fn);b.id='sub-action-'+action+'-'+s.id;return b;};
  if(!otherEnvironment(s)){
   if(s.provider==='toss'&&!s.review_required){if(s.status==='pending_card')actions.append(actionButton('카드 등록 계속','continue',()=>act(s,'continue')));if(['active','past_due','paused'].includes(s.status)){actions.append(actionButton('카드 변경','card',()=>act(s,'card')));if(s.status==='paused')actions.append(actionButton('구독 재개','resume',()=>act(s,'resume')));else actions.append(actionButton('일시정지','pause',()=>act(s,'pause')));if(s.status==='past_due')actions.append(actionButton('결제 다시 시도','retry',()=>act(s,'retry')));}}
   if(s.provider==='paypal'&&!['CANCELLED','EXPIRED'].includes(s.status))actions.append(actionButton('구독 상태 확인','sync',()=>act(s,'sync')));
   if(s.provider==='paypal'&&s.approval_url&&s.status==='APPROVAL_PENDING'&&!s.review_required)actions.append(actionButton('승인 계속','continue',()=>act(s,'continue')));
   if(s.renew||['pending_card','paused','SUSPENDED','APPROVAL_PENDING','APPROVED','CREATING','CREATE_UNKNOWN'].includes(s.status))actions.append(actionButton(unpaidApplication(s)?'신청 취소':'구독 해지','cancel-open',()=>{state.confirmCancel=s.id;state.rowFeedback=null;render();document.getElementById('sub-action-cancel-confirm-'+s.id)?.focus();}));
  }
  const more=actionButton('상세','details',()=>{if(state.expandedIds.has(s.id))state.expandedIds.delete(s.id);else state.expandedIds.add(s.id);render();});more.setAttribute('aria-expanded',String(state.expandedIds.has(s.id)));more.setAttribute('aria-controls','sub-details-'+s.id);actions.append(more);
  row.append(heading,amount,status,actions);panel.append(row);
  if(state.busyId===s.id){const note=node('p','구독 내역을 확인하고 있습니다.','sub-history-feedback sub-note');note.id='sub-feedback-'+s.id;note.setAttribute('role','status');panel.append(note);}
  else if(state.rowFeedback?.id===s.id){const note=node('p',state.rowFeedback.text,'sub-history-feedback sub-note'+(state.rowFeedback.error?' error':''));note.id='sub-feedback-'+s.id;note.setAttribute('role','status');panel.append(note);}
  const details=E('div',null,'sub-history-details');details.id='sub-details-'+s.id;details.hidden=!state.expandedIds.has(s.id);
  const dl=E('dl',null,'sub-detail'),values=unpaidApplication(s)?[['결제 예정 금액',money(s.amount_minor,s.currency)]]:[['정기결제 금액',money(s.amount_minor,s.currency)],['다음 결제일',s.renew?date(s.next_charge_at):t('자동 갱신 중단')],['이용 기간 종료일',date(s.period_end)]];for(const [label,value] of values){const v=E('dd',value);v.dataset.webrUserContent='';dl.append(node('dt',label),v);}details.append(dl);const reference=E('p',s.id,'sub-id');reference.dataset.webrUserContent='';details.append(reference);if(otherEnvironment(s))details.append(node('p','현재 서버에서는 이 구독을 관리할 수 없습니다.','sub-note error'));
  if(state.confirmCancel===s.id){const confirm=E('div',null,'sub-confirm');confirm.append(node('p',unpaidApplication(s)?'아직 결제되지 않은 신청을 취소할까요?':'다음 갱신부터 자동결제를 중단할까요?'),actionButton('해지 확정','cancel-confirm',()=>act(s,'cancel')),actionButton('돌아가기','cancel-back',()=>{state.confirmCancel='';render();}));panel.append(confirm);}panel.append(details);return panel;}
 async function loadSDK(){if(global.TossPayments)return;if(!sdkPromise)sdkPromise=new Promise((resolve,reject)=>{const script=E('script');script.src='https://js.tosspayments.com/v2/standard';script.onload=resolve;script.onerror=()=>{sdkPromise=null;script.remove();reject(Error('unavailable'));};document.head.append(script);});await sdkPromise;if(!global.TossPayments)throw Error('unavailable');}
 function safeLocal(url){const u=new URL(url);if(u.origin!==location.origin||u.pathname!=='/intro/membership/subscription/return/')throw Error('invalid_input');return u.href;}
 async function approval(s){if(!uuid.test(s.id))throw Error('invalid_input');try{sessionStorage.setItem('webr-subscription-intent',JSON.stringify({id:s.id,provider:s.provider}));}catch(_){}
 if(s.provider==='toss'){if(!s.client_key||!s.customer_key)throw Error('unavailable');await loadSDK();await global.TossPayments(s.client_key).payment({customerKey:s.customer_key}).requestBillingAuth({method:'CARD',successUrl:safeLocal(s.success_url),failUrl:safeLocal(s.fail_url)});
 }else{const u=new URL(s.approval_url);if(u.protocol!=='https:'||u.username||u.password||!['www.paypal.com','www.sandbox.paypal.com'].includes(u.hostname)||u.port||!['/webapps/billing/subscriptions','/webapps/billing/subscriptions/'].includes(u.pathname))throw Error('invalid_input');location.assign(u.href);}}
 async function create(){if(state.busy||!state.consent||!unit())return;state.busy=true;state.message='';render();try{state.request=state.request||crypto.randomUUID();const result=await api(base(state.provider),{request_id:state.request,product_id:state.product,interval:state.interval,quantity:team()?state.quantity:1,expected_unit_amount_minor:unit(),consent:true,consent_version:'2026-09-06'});await approval(result);}catch(e){message(e);if(e.message==='quote_changed'){state.consent=false;state.request=null;try{state.settings=await api('/api/subscriptions/config/',undefined,10000);state.configError=!state.settings.toss?.enabled&&!state.settings.paypal?.enabled;}catch(_){state.settings={};state.configError=true;}}}finally{state.busy=false;render();}}
 async function refresh(manual=false){
  if(state.busy)return;state.busy=true;state.busyId='';state.rowFeedback=null;state.listPending=true;state.listsComplete=false;state.listFeedback=manual?{text:'구독 내역을 확인하고 있습니다.',error:false}:null;render();
  try{
   const providers=['toss','paypal'],results=await Promise.allSettled(providers.map(p=>api(base(p),undefined,10000))),previous=state.subscriptions;
   state.subscriptions=results.flatMap((r,i)=>r.status==='fulfilled'?r.value:previous.filter(s=>s.provider===providers[i]));state.listsComplete=results.every(r=>r.status==='fulfilled');state.login=false;state.message='';state.error=false;
   const failed=results.find(r=>r.status==='rejected');if(failed){message(failed.reason);state.listFeedback={text:state.message,error:true};}
   if(manual&&!state.listFeedback?.error)state.listFeedback={text:'구독 정보를 확인했습니다.',error:false};
  }catch(e){message(e);state.listFeedback={text:state.message,error:true};}finally{state.busy=false;state.busyId='';state.listPending=false;render();}
 }
 async function act(s,action){
  if(state.busy||otherEnvironment(s))return;state.busy=true;state.busyId=s.id;state.rowFeedback=null;state.listFeedback=null;state.message='';state.error=false;render();
  try{
   const result=s.provider==='paypal'&&['continue','sync'].includes(action)?await api(base('paypal',s.id)+'sync/',{},15000):action==='continue'?await api(base(s.provider,s.id),undefined,15000):await api(base(s.provider,s.id)+action+'/',{},15000);
   state.subscriptions=state.subscriptions.map(x=>x.id===result.id?result:x);if(callback?.id===result.id)callback.result=result;
   if(action==='continue'&&s.provider==='paypal'){
    if(result.review_required)throw Error('review_required');
    if(result.status==='APPROVAL_PENDING'){if(!result.approval_url)throw Error('approval_unavailable');state.rowFeedback={id:s.id,text:'결제창을 준비하고 있습니다.',error:false};render();await approval(result);}
    else state.rowFeedback={id:s.id,text:'구독 정보를 확인했습니다.',error:false};
   }else if(action==='continue'||action==='card'){state.rowFeedback={id:s.id,text:'결제창을 준비하고 있습니다.',error:false};render();await approval(result);}
   else state.rowFeedback={id:s.id,text:action==='cancel'?(unpaidApplication(s)?'신청을 취소했습니다.':'자동 갱신을 중단했습니다.'):result.review_required?'결제 상태 확인 필요':'구독 정보를 확인했습니다.',error:!!result.review_required};
   state.confirmCancel='';
  }catch(e){
   if(s.provider==='paypal'&&['sync','continue'].includes(action)&&e.message==='approval_unavailable'){
    try{const current=await api(base('paypal',s.id),undefined,10000);state.subscriptions=state.subscriptions.map(x=>x.id===current.id?current:x);if(callback?.id===current.id)callback.result=current;}catch(_){}
   }
   message(e);state.rowFeedback={id:s.id,text:state.message,error:true};
  }
  finally{state.busy=false;state.busyId='';render();if(action==='cancel'){const note=document.getElementById('sub-feedback-'+s.id);if(note){note.tabIndex=-1;note.focus();}}}
 }
 function renderCallback(page){page.append(node('h2',callback.canceled?'결제가 취소되었습니다.':'구독 상태 확인'));if(callback.result)page.append(subscriptionCard(callback.result));else page.append(node('p','결제 상태를 확인하고 있습니다.','sub-note'));const actions=E('div',null,'sub-actions');actions.append(button('다시 확인',()=>checkCallback(!callback.canceled&&(!!callback.authKey||callback.provider==='paypal'))),link('내 구독','/intro/membership/subscription/'));page.append(actions);}
 async function checkCallback(confirm){if(state.busy||closed||!uuid.test(callback.id)||!['toss','paypal'].includes(callback.provider))return;state.busy=true;clearTimeout(poll);render();try{let result;
 if(confirm&&!callback.canceled&&callback.provider==='toss'&&callback.authKey&&callback.customerKey){result=await api(base('toss',callback.id)+'confirm/',{auth_key:callback.authKey,customer_key:callback.customerKey});callback.authKey='';callback.customerKey='';}
 else if(confirm&&!callback.canceled&&callback.provider==='paypal')result=await api(base('paypal',callback.id)+'sync/',{});
 else result=await api(base(callback.provider,callback.id));callback.result=result;state.message=callback.canceled?'결제가 취소되었습니다.':result.review_required?'결제 상태 확인 필요':result.period_end?'구독 정보를 확인했습니다.':'결제 확인 후 회원 권한이 적용됩니다. 잠시 후 다시 확인해 주세요.';state.error=!!result.review_required;
 if(!callback.canceled&&!result.period_end&&!result.review_required&&pollCount++<5)poll=setTimeout(()=>checkCallback(false),3000);
 }catch(e){message(e);}finally{state.busy=false;render();}}
 async function loadUserInfo(){if(!global.gv_username)return;state.userInfoPending=true;render();try{const response=await fetch('/account/ajax_get_userinfo/',{method:'POST',credentials:'same-origin',cache:'no-store'});const data=await response.json();if(response.ok&&!data.error&&data.email)state.userinfo=data;}catch(_){}finally{state.userInfoPending=false;render();}}
 async function loadInitial(){if(state.catalogPending||state.configPending)return;const first=!state.loaded;state.loaded=true;state.catalogPending=true;state.configPending=true;state.catalogError=false;state.configError=false;state.settings={};render();if(first)void loadUserInfo();const catalog=api('/ajax_membership_products/',{},10000).then(data=>{state.products=productsIDs.map(id=>(data.products||[]).find(p=>p.uuid===id)).filter(Boolean);state.catalogError=!state.products.length;},()=>{state.catalogError=true;}).finally(()=>{state.catalogPending=false;render();});const config=api('/api/subscriptions/config/',undefined,10000).then(data=>{state.settings=data;state.configError=!data.toss?.enabled&&!data.paypal?.enabled;if(first&&!data.toss?.enabled&&data.paypal?.enabled)state.provider='paypal';},()=>{state.settings={};state.configError=true;}).finally(()=>{state.configPending=false;render();});await Promise.allSettled([catalog,config]);if(first)await refresh();}
 global.set_main=async function(){host=document.getElementById('div_main');if(!host||host.querySelector('[data-subscription-page]'))return;mountStyles();const u=new URL(location.href);if(u.pathname.endsWith('/subscription/return/')){callback={id:u.searchParams.get('id')||'',provider:u.searchParams.get('provider')||'',authKey:u.searchParams.get('authKey')||'',customerKey:u.searchParams.get('customerKey')||'',canceled:u.searchParams.get('cancel')==='1'};const safe=new URLSearchParams({provider:callback.provider,id:callback.id});if(callback.canceled)safe.set('cancel','1');history.replaceState(null,'',u.pathname+'?'+safe);render();if(uuid.test(callback.id))await checkCallback(true);else{state.message='요청을 완료하지 못했습니다. 내 구독에서 상태를 확인해 주세요.';state.error=true;render();}return;}
 render();await loadInitial();};
 global.addEventListener('webr:language-change',render);global.addEventListener('pagehide',()=>{closed=true;clearTimeout(poll);if(callback){callback.authKey='';callback.customerKey='';}},{once:true});
})(window);
