function Div_article_read_comment(props) {
  function Div_comment_header(props2) {
    return /* @__PURE__ */ React.createElement("div", { class: "flex flex-row justify-start items-center space-x-2" }, /* @__PURE__ */ React.createElement(Span_btn_user, { user_nickname: props2.data.user_nickname, role: props2.data.user_role }), /* @__PURE__ */ React.createElement(Span_btn_date, { date: props2.data.created_at }), /* @__PURE__ */ React.createElement(Span_btn_comment_secret, { toggle: props2.data.is_secret }), /* @__PURE__ */ React.createElement(Span_btn_my_comment, { toggle: props2.data.check_comment_reader }));
  }
  function Div_comment(props2) {
    const isDepth2 = props2.depth === 2;
    const bgColorClass = props2.data.user_writer == 1 ? isDepth2 ? "bg-blue-100 border border-blue-700" : "bg-blue-50" : isDepth2 ? "bg-gray-200 border border-gray-700" : "bg-gray-100";
    const comment_depth2_list = !isDepth2 && Object.keys(props2.data.rereply || {}).map(
      (btn_data) => /* @__PURE__ */ React.createElement(Div_comment, { data: props2.data.rereply[btn_data], depth: 2 })
    );
    return /* @__PURE__ */ React.createElement("article", { class: `p-6 ${isDepth2 ? "ml-4" : ""} text-base ${bgColorClass} rounded-xl w-full space-y-2` }, /* @__PURE__ */ React.createElement("div", { class: "flex justify-between items-center space-x-2" }, /* @__PURE__ */ React.createElement(Div_comment_header, { data: props2.data })), /* @__PURE__ */ React.createElement("div", { class: "text-gray-500", id: "div_comment_" + props2.data.uuid }), props2.data.file_url != null && /* @__PURE__ */ React.createElement("div", { class: "flex flex-row justify-start items-center space-x-2 text-sm hover:underline" }, /* @__PURE__ */ React.createElement("p", null, /* @__PURE__ */ React.createElement("svg", { class: "size-4", viewBox: "0 0 48 48", fill: "none", xmlns: "http://www.w3.org/2000/svg" }, /* @__PURE__ */ React.createElement("g", { id: "SVGRepo_bgCarrier", "stroke-width": "0" }), /* @__PURE__ */ React.createElement("g", { id: "SVGRepo_tracerCarrier", "stroke-linecap": "round", "stroke-linejoin": "round" }), /* @__PURE__ */ React.createElement("g", { id: "SVGRepo_iconCarrier" }, " ", /* @__PURE__ */ React.createElement("rect", { width: "48", height: "48", fill: "white", "fill-opacity": "0.01" }), " ", /* @__PURE__ */ React.createElement("path", { d: "M41 4H7C5.34315 4 4 5.34315 4 7V41C4 42.6569 5.34315 44 7 44H41C42.6569 44 44 42.6569 44 41V7C44 5.34315 42.6569 4 41 4Z", fill: "#2F88FF", stroke: "#000000", "stroke-width": "4", "stroke-linejoin": "round" }), " ", /* @__PURE__ */ React.createElement("path", { d: "M34 4V22H15V4H34Z", fill: "#43CCF8", stroke: "white", "stroke-width": "4", "stroke-linejoin": "round" }), " ", /* @__PURE__ */ React.createElement("path", { d: "M29 11V15", stroke: "white", "stroke-width": "4", "stroke-linecap": "round" }), " ", /* @__PURE__ */ React.createElement("path", { d: "M11.9969 4H36.9985", stroke: "#000000", "stroke-width": "4", "stroke-linecap": "round" }), " "))), /* @__PURE__ */ React.createElement("a", { href: window.location.protocol + "//" + window.location.host + "/" + props2.data.file_url, target: "_blank" }, props2.data.file_name)), /* @__PURE__ */ React.createElement("div", { class: "w-full", id: "div_comment_footer_" + props2.data.uuid }, isDepth2 ? /* @__PURE__ */ React.createElement(Div_comment_depth2_button_list, { data: props2.data }) : /* @__PURE__ */ React.createElement(Div_comment_depth1_button_list, { data: props2.data, is_secret: props2.is_secret, check_reader: props2.check_reader })), comment_depth2_list, !isDepth2 && /* @__PURE__ */ React.createElement("div", { id: "div_community_read_comment_new_" + props2.data.uuid, class: "hidden" }, /* @__PURE__ */ React.createElement(Div_comment_form, { title: "\uB300\uB313\uAE00 \uC4F0\uAE30", class: "mt-4 p-4 bg-white rounded-lg w-full space-y-2", uuid_comment: props2.data.uuid })));
  }
  const comment_list = Object.keys(props.data).map(
    (btn_data) => /* @__PURE__ */ React.createElement(Div_comment, { data: props.data[btn_data], depth: 1, is_secret: props.is_secret, check_reader: props.check_reader })
  );
  return /* @__PURE__ */ React.createElement("section", { class: "bg-white py-8 lg:py-16 antialiased" }, /* @__PURE__ */ React.createElement("div", { class: "w-full mx-auto px-4 space-y-2" }, /* @__PURE__ */ React.createElement("div", { class: "flex justify-between items-center mb-6" }, /* @__PURE__ */ React.createElement("h2", { class: "text-lg lg:text-2xl font-bold text-gray-900" }, "\uB313\uAE00 (", props.data.length, ")")), /* @__PURE__ */ React.createElement("form", { class: "mb-6" }, /* @__PURE__ */ React.createElement("div", { class: "mb-4 w-full bg-gray-50 rounded-lg border border-gray-200" }, /* @__PURE__ */ React.createElement("div", { id: "div_comment_new", class: "w-full" }))), /* @__PURE__ */ React.createElement("div", { class: "flex flex-col justify-center items-end w-full space-y-2" }, comment_list), gv_username !== "" && /* @__PURE__ */ React.createElement("div", { class: "flex flex-row justify-center items-center p-6 text-base bg-gray-100 rounded-xl w-full", id: "div_community_read_comment_new" }, /* @__PURE__ */ React.createElement(Div_comment_form, { title: "\uB313\uAE00 \uC4F0\uAE30", class: "w-full space-y-2", uuid_comment: null }))));
}
